#= ENTITY_SHADOW
entity.1599=minecraft:entity_shadow
#= ENTITY_NAME_TAG
entity.1600=minecraft:name_tag

#$
#= ENTITY_PLAYER
entity.1601=player \
 corpse:corpse

#= ENTITY_LIGHTNING
entity.*= minecraft:lightning_bolt weather2:lightning_bolt

#$
## misc stuff

#= ENTITY_BLAZE
entity.*= blaze minecraft:entity_flame
# TODO: Why is entity flame in both `ENTITY_SPECTRAL_ARROW` and `ENTITY_BLAZE` ???

#= ENTITY_DRAGON_WITHER
entity.*= ender_dragon wither

#= ENTITY_END_CRYSTAL
entity.*= end_crystal

#= ENTITY_GLOW_SQUID
entity.*= glow_squid

#= ENTITY_ITEM_FRAME
entity.*= item_frame item_display

#= ENTITY_MAGMA_CUBE
entity.*= magma_cube \
 luminous_beasts:rare_executioner luminous_beasts:ember luminous_beasts:soul_ember luminous_beasts:the_furnace luminous_beasts:soul_furnace

#= ENTITY_TNT
entity.*= tnt firework_rocket

#= ENTITY_FIREBALL_SMALL
entity.*= small_fireball

#= ENTITY_SPECTRAL_ARROW
entity.*= spectral_arrow bigglobe:torch_arrow entity_flame
# TODO: Why is entity flame in both `ENTITY_SPECTRAL_ARROW` and `ENTITY_BLAZE` ???

################################################
###### SUB-SURFACE SCATTERING
################################################

## medium sss (same as strong sss for blocks)
#= ENTITY_SSS_MEDIUM
entity.1801 = giant ghast elder_guardian \
 naturalist:butterfly naturalist:firefly naturalist:caterpillar naturalist:dragonfly

## weak sss (same as weak sss for blocks)
#= ENTITY_SSS_WEAK
entity.* = furnace_minecart sheep frog chicken iron_golem snow_golem polar_bear zombie_horse armor_stand arrow squid bat cat cod cow donkey fox horse mooshroom mule ocelot parrot pig piglin polar_bear pufferfish rabbit salmon strider tropical_fish turtle villager wandering_trader bee cave_spider dolphin enderman llama panda spider wolf zombified_piglin creeper drowned endermite evoker guardian hoglin husk phantom piglin_brute pillager ravager silverfish stray vex vindicator witch zoglin zombie zombie_villager trader_llama \
 naturalist:bear naturalist:snail naturalist:snake naturalist:coral_snake naturalist:rattlesnake naturalist:bluejay naturalist:cardinal naturalist:canary naturalist:robin naturalist:finch naturalist:sparrow naturalist:rhino naturalist:elephant naturalist:lion naturalist:zebra naturalist:giraffe naturalist:hippo naturalist:vulture naturalist:boar naturalist:catfish naturalist:alligator naturalist:bass naturalist:tortoise naturalist:duck \
 creeperoverhaul:jungle_creeper creeperoverhaul:bamboo_creeper creeperoverhaul:desert_creeper creeperoverhaul:badlands_creeper creeperoverhaul:hills_creeper creeperoverhaul:savannah_creeper creeperoverhaul:mushroom_creeper creeperoverhaul:swamp_creeper creeperoverhaul:dripstone_creeper creeperoverhaul:cave_creeper creeperoverhaul:dark_oak_creeper creeperoverhaul:spruce_creeper creeperoverhaul:beach_creeper creeperoverhaul:snowy_creeper creeperoverhaul:ocean_creeper creeperoverhaul:birch_creeper \
 fowlplay:blue_jay fowlplay:cardinal fowlplay:chickadee fowlplay:crow fowlplay:duck fowlplay:gull fowlplay:hawk fowlplay:penguin fowlplay:pigeon fowlplay:raven fowlplay:robin fowlplay:sparrow \
 luminous_beasts:tree_ent luminous_beasts:cherry_tree_ent luminous_beasts:hermit_king luminous_beasts:sand_crab luminous_beasts:rare_hermit_king luminous_beasts:mummy luminous_beasts:rare_mummy luminous_beasts:yeti luminous_beasts:rare_yeti luminous_beasts:vile_gator luminous_beasts:rare_vile_gator luminous_beasts:baby_phoenix luminous_beasts:rare_baby_phoenix luminous_beasts:bone_stalker luminous_beasts:stalker luminous_beasts:rare_bone_stalker luminous_beasts:rare_stalker luminous_beasts:piglin_executioner luminous_beasts:crimson_spitter luminous_beasts:rare_crimson_spitter luminous_beasts:horseless_headsman luminous_beasts:the_scarecrow luminous_beasts:pumpkin_minion luminous_beasts:scarecrow_minion luminous_beasts:phoenixbird luminous_beasts:rare_phoenix_bird luminous_beasts:gilded_ent \
 luminous_monsters:miner_zombie luminous_monsters:miner_skeleton luminous_monsters:glacial_zombie luminous_monsters:glacial_skeleton luminous_monsters:swamp_zombie luminous_monsters:swamp_skeleton luminous_monsters:dark_oak_zombie luminous_monsters:dark_oak_skeleton luminous_monsters:hollow luminous_monsters:sunken luminous_monsters:crimson_walker luminous_monsters:revenant luminous_monsters:cherry_zombie luminous_monsters:cherry_skeleton luminous_monsters:savanna_zombie luminous_monsters:savanna_skeleton
#removed: player blaze magma_cube

################################################
###### REFLECTIVE TRANSLUCENTS
################################################

#= ENTITY_SLIME
entity.* = slime
