#if ENTITY_SHADOW_AMOUNT < 1 || !defined COLORWHEEL_SHADOWMAP
    shadow.enabled = false
#else
    shadow.enabled = true
#endif

blend.clrwl_gbuffers_translucent = SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE_MINUS_DST_ALPHA ONE
blend.clrwl_gbuffers_glint = ONE ONE ONE ZERO
blend.clrwl_shadow = ONE ZERO ONE ZERO

#  Disable blending
blend.clrwl_gbuffers = off
blend.clrwl_gbuffers_damagedblock = off

# this is important for refraction and glass tint to work correctly
blend.clrwl_gbuffers_translucent.colortex11 = off

#ifdef COLORWHEEL_OIT
    oit = true
#else
    oit = false
#endif

# thanks you Merlin
oit.gbuffers.coefficientRanks = 3,3

oit.gbuffers.colortex2 = 0
oit.gbuffers.colortex2.format = RGBA16F

oit.gbuffers.colortex7 = 1
oit.gbuffers.colortex7.format = RGBA8

oit.gbuffers.colortex11 = frontmost
oit.gbuffers.colortex11.format = RGBA16

oit.gbuffers.colortex14 = frontmost
oit.gbuffers.colortex14.format = RGBA16F